Repository waic/wcag21, pull requests merged in 2021-07, with the labels that each got.

#1015 20210701レビューコメント対応
  understanding/intro.html
Labels: 解説書-v2

#1016 達成基準 1.1.1 の翻訳漏れと思われる文章の追加
  guidelines/index.html
Labels: WCAG21

#1010 H49を作業しました。
  techniques/html/H49.html
  techniques/index.html
Labels: 達成方法集-201910

#1018 達成方法集 H83の翻訳
  techniques/html/H83.html
  techniques/index.html
Labels: 達成方法集-201910

#1017 H51の作業をしました。
  techniques/html/H51.html
  techniques/index.html
Labels: 達成方法集-201910

#1009 H48の作業をしました。
  techniques/html/H48.html
  techniques/index.html
Labels: 達成方法集-201910

#1019 H53を作業しました。
  techniques/html/H53.html
  techniques/index.html
Labels: 達成方法集-201910

#987 H37作業（Issue 864 ）
  techniques/html/H37.html
Labels: 達成方法集-201910

#1025 達成方法集 H76の翻訳
  techniques/html/H76.html
  techniques/index.html
Labels: 達成方法集-201910

#1026 達成方法集 H75の翻訳
  techniques/html/H75.html
  techniques/index.html
Labels: 達成方法集-201910

#1028 達成方法集 H73の翻訳
  techniques/html/H73.html
  techniques/index.html
Labels: 達成方法集-201910

#1021 達成方法集 H80の翻訳
  techniques/html/H80.html
  techniques/index.html
Labels: 達成方法集-201910

#1022 達成方法集 H79の翻訳
  techniques/html/H79.html
  techniques/index.html
Labels: 達成方法集-201910

#1024 達成方法集 H77の翻訳
  techniques/html/H77.html
  techniques/index.html
Labels: 達成方法集-201910

#1029 達成方法集 H71の翻訳
  techniques/html/H71.html
  techniques/index.html
Labels: 達成方法集-201910

#1023 達成方法集 H78の翻訳
  techniques/html/H78.html
  techniques/index.html
Labels: 達成方法集-201910

#1027 達成方法集 H74の翻訳
  techniques/html/H74.html
  techniques/index.html
Labels: 達成方法集-201910

#1037 達成方法集 H63の翻訳
  techniques/html/H63.html
  techniques/index.html
Labels: 達成方法集-201910

#1038 達成方法集 H62の翻訳
  techniques/html/H62.html
  techniques/index.html
Labels: 達成方法集-201910

#1039 達成方法集 H60の翻訳
  techniques/html/H60.html
  techniques/index.html
Labels: 達成方法集-201910

#1040 達成方法集 H59の翻訳
  techniques/html/H59.html
  techniques/index.html
Labels: 達成方法集-201910

#1042 達成方法集 H57の翻訳
  techniques/html/H57.html
  techniques/index.html
Labels: 達成方法集-201910

#1046 達成方法集 CSS6の翻訳
  techniques/css/C6.html
  techniques/index.html
Labels: 達成方法集-201910

#1032 達成方法集 H65の翻訳
  techniques/html/H65.html
  techniques/index.html
Labels: 達成方法集-201910

#1041 達成方法集 H58の翻訳
  techniques/html/H58.html
  techniques/index.html
Labels: 達成方法集-201910

#1047 達成方法集 CSS7の翻訳
  techniques/css/C7.html
  techniques/index.html
Labels: 達成方法集-201910
