Repository waic/wcag21, pull requests merged in 2021-08, with the labels that each got.

#1064 H56の作業をしました。
  techniques/html/H56.html
  techniques/index.html
Labels: 達成方法集-201910

#1063 H54の作業をしました。
  techniques/html/H54.html
  techniques/index.html
Labels: 達成方法集-201910

#1050 達成方法集 CSS8の翻訳
  techniques/css/C8.html
  techniques/index.html
Labels: 達成方法集-201910

#1051 達成方法集 CSS9の翻訳
  techniques/css/C9.html
  techniques/index.html
Labels: 達成方法集-201910

#1052 達成方法集 CSS12の翻訳
  techniques/css/C12.html
  techniques/index.html
Labels: 達成方法集-201910

#1054 達成方法集 CSS14の翻訳
  techniques/css/C14.html
  techniques/index.html
Labels: 達成方法集-201910

#1057 達成方法集 CSS18の翻訳
  techniques/css/C18.html
  techniques/index.html
Labels: 達成方法集-201910

#1058 達成方法集 CSS19の翻訳
  techniques/css/C19.html
  techniques/index.html
Labels: 達成方法集-201910

#1059 達成方法集 CSS20の翻訳
  techniques/css/C20.html
  techniques/index.html
Labels: 達成方法集-201910

#1060 達成方法集 CSS21の翻訳
  techniques/css/C21.html
  techniques/index.html
Labels: 達成方法集-201910

#1065 達成方法集 CSS23の翻訳
  techniques/css/C23.html
  techniques/index.html
Labels: 達成方法集-201910

#1066 達成方法集 CSS24の翻訳
  techniques/css/C24.html
  techniques/index.html
Labels: 達成方法集-201910

#1067 達成方法集 CSS25の翻訳
  techniques/css/C25.html
  techniques/index.html
Labels: 達成方法集-201910

#1069 達成方法集 CSS28の翻訳
  techniques/css/C28.html
  techniques/index.html
Labels: 達成方法集-201910

#1055 達成方法集 CSS15の翻訳
  techniques/css/C15.html
  techniques/index.html
Labels: 達成方法集-201910

#1070 解説書1.4.13の2020年12月2日版への更新
  understanding/content-on-hover-or-focus.html
Labels: 解説書-v2

#1056 達成方法集 CSS17の翻訳
  techniques/css/C17.html
  techniques/index.html
Labels: 達成方法集-201910

#1030 達成方法集 H69の翻訳
  techniques/html/H69.html
  techniques/index.html
Labels: 達成方法集-201910

#1068 達成方法集 CSS27の翻訳
  techniques/css/C27.html
  techniques/general/G57.html
  techniques/general/G59.html
  techniques/index.html
  understanding/focus-order.html
  understanding/meaningful-sequence.html
Labels: 達成方法集-201910

#1072 達成方法集 CSS29の翻訳
  techniques/css/C29.html
  techniques/index.html
Labels: 達成方法集-201910

#1073 達成方法集 CSS30の翻訳
  techniques/css/C30.html
  techniques/index.html
Labels: 達成方法集-201910

#1075 G161のタイトル修正
  techniques/general/G161.html
Labels: 達成方法集-201910

#1074 C31のタイトル変更と関連するテキストの修正
  techniques/css/C31.html
  techniques/css/C32.html
  techniques/failures/F105.html
  techniques/index.html
  understanding/reflow.html
Labels: 達成方法集-201910, 解説書-v2

#1081 解説書SC 2.2.2を2020年12月2日版に更新
  understanding/pause-stop-hide.html
Labels: 解説書-v2

#1096 G135のタイトル変更
  techniques/general/G108.html
  techniques/general/G135.html
  techniques/index.html
  techniques/pdf/PDF10.html
  techniques/pdf/PDF12.html
  understanding/name-role-value.html
Labels: 達成方法集-201910

#1095 G96のタイトル変更
  techniques/failures/F14.html
  techniques/general/G96.html
  techniques/index.html
  understanding/sensory-characteristics.html
Labels: 達成方法集-201910

#1097 達成方法集 H90の翻訳
  techniques/html/H90.html
  techniques/index.html
Labels: 達成方法集-201910

#1080 github.ioへのリンクを置換
  techniques/client-side-script/SCR28.html
  techniques/client-side-script/SCR36.html
  techniques/client-side-script/SCR38.html
  techniques/css/C33.html
  techniques/css/C38.html
  techniques/css/C39.html
  techniques/failures/F65.html
  techniques/failures/F72.html
  techniques/general/G136.html
  techniques/general/G159.html
  techniques/general/G160.html
  techniques/general/G161.html
  techniques/general/G17.html
  techniques/general/G172.html
  techniques/general/G174.html
  techniques/general/G18.html
  techniques/general/G183.html
  techniques/general/G188.html
  techniques/general/G189.html
  techniques/general/G191.html
  techniques/general/G202.html
  techniques/general/G206.html
  techniques/general/G55.html
  techniques/html/H54.html
  techniques/server-side-script/SVR2.html
  techniques/server-side-script/SVR3.html
  techniques/silverlight/SL12.html
  techniques/silverlight/SL14.html
  techniques/silverlight/SL15.html
  techniques/silverlight/SL16.html
  techniques/silverlight/SL18.html
  techniques/silverlight/SL19.html
  techniques/silverlight/SL24.html
  techniques/silverlight/SL26.html
  techniques/silverlight/SL28.html
  techniques/silverlight/SL29.html
  techniques/silverlight/SL3.html
  techniques/silverlight/SL30.html
  techniques/silverlight/SL4.html
  techniques/silverlight/SL8.html
Labels: 達成方法集-201910

#1071 解説書 1.4.8の更新
  understanding/visual-presentation.html
Labels: 解説書-v2

#1078 ACTルールに関連する解説書ページの翻訳
  understanding/index.html
  understanding/language-of-page.html
  understanding/name-role-value.html
  understanding/page-titled.html
  understanding/text-alternatives.html
  understanding/understanding-act-rules.html
  understanding/understanding-techniques.html
Labels: 解説書-v2

#1083 解説書SC 1.3.6の2020年12月2日版への更新
  understanding/identify-purpose.html
Labels: 解説書-v2

#1084 解説書SC 2.2.6の2020年12月2日版への更新
  understanding/timeouts.html
Labels: 解説書-v2

#1085 解説書SC 2.3.3の2020年12月2日版への更新
  understanding/animation-from-interactions.html
Labels: 解説書-v2

#1086 解説書SC 2.5.2の2020年12月2日版への更新
  understanding/pointer-cancellation.html
Labels: 解説書-v2

#1087 解説書SC 2.5.5の2020年12月2日版への更新
  understanding/target-size.html
Labels: 解説書-v2

#1088 解説書SC 2.5.6の2020年12月2日版への更新
  understanding/concurrent-input-mechanisms.html
Labels: 解説書-v2

#1089 解説書SC 4.1.3の2020年12月2日版への更新
  understanding/status-messages.html
Labels: 解説書-v2

#1093 解説書SC 2.5.4の2020年12月2日版への更新
  understanding/motion-actuation.html
Labels: 解説書-v2

#1094 解説書SC 1.3.4の2020年12月2日版への更新
  understanding/orientation.html
Labels: 解説書-v2

#1100 達成方法集 H86の翻訳
  techniques/html/H86.html
  techniques/index.html
Labels: 達成方法集-201910

#1105 f2を作業しました。
  techniques/failures/F2.html
  techniques/index.html
Labels: 達成方法集-201910

#1090 解説書SC 1.4.12の2020年12月2日版への更新
  understanding/text-spacing.html
Labels: 解説書-v2

#1108 WAIC翻訳文書のライセンスへのリンクを追加
  guidelines/index.html
Labels: WCAG21

#1116 関連文書の訳注にライセンスへのリンクを追加
  techniques/index.html
  understanding/index.html
Labels: 達成方法集-201910, 解説書-v2

#1117 日本語訳リンクの処理でTechniquesのURLも置換対象にした
  guidelines/waic_link.js
Labels: WCAG21

#1109 F96 a終了タグ追加
  techniques/failures/F96.html
Labels: 達成方法集-201910
