Repository waic/wcag21, pull requests merged in 2021-05, with the labels that each got.

#954 ARIA8にて、WCAG 2.0の訳を反映 #685
  techniques/aria/ARIA8.html
Labels: 達成方法集-201910

#950 解説書：重要な用語の修正
  understanding/audio-only-and-video-only-prerecorded.html
  understanding/audio-only-live.html
  understanding/contrast-enhanced.html
  understanding/contrast-minimum.html
  understanding/info-and-relationships.html
  understanding/low-or-no-background-audio.html
  understanding/media-alternative-prerecorded.html
  understanding/non-text-contrast.html
Labels: 解説書-v2

#949 解説書：タイトルの修正
  understanding/meaningful-sequence.html
  understanding/no-keyboard-trap.html
  understanding/orientation.html
  understanding/section-headings.html
Labels: 解説書-v2

#947 解説書：訳注の修正
  understanding/audio-description-or-media-alternative-prerecorded.html
  understanding/audio-description-prerecorded.html
  understanding/captions-live.html
  understanding/captions-prerecorded.html
  understanding/change-on-request.html
  understanding/contrast-enhanced.html
  understanding/contrast-minimum.html
  understanding/extended-audio-description-prerecorded.html
  understanding/focus-order.html
  understanding/headings-and-labels.html
  understanding/keyboard.html
  understanding/language-of-parts.html
  understanding/media-alternative-prerecorded.html
  understanding/navigable.html
  understanding/page-titled.html
  understanding/pause-stop-hide.html
  understanding/resize-text.html
  understanding/use-of-color.html
Labels: 解説書-v2

#957 Update ARIA5.html
  techniques/aria/ARIA5.html
  techniques/index.html
Labels: 達成方法集-201910

#955 ARIA10にて、WCAG 2.0の訳を反映 #687
  techniques/aria/ARIA10.html
Labels: 達成方法集-201910

#958 ARIA8とARIA10の翻訳に伴うindex.htmlの修正
  techniques/index.html
Labels: 達成方法集-201910

#956 翻訳抜け箇所の修正
  understanding/documenting-accessibility-support.html
  understanding/refer-to-wcag.html
Labels: 解説書-v2

#963 達成方法集 ARIA21 の翻訳（Issue698）
  techniques/aria/ARIA21.html
Labels: 置換作業済み, 達成方法集-201910

#964 達成方法集 ARIA20 の翻訳（Issue697）
  techniques/aria/ARIA20.html
Labels: 置換作業済み, 達成方法集-201910

#965 達成方法集 ARIA9 の翻訳
  techniques/aria/ARIA9.html
  techniques/index.html
Labels: 達成方法集-201910
