Repository waic/wcag21, pull requests merged in 2021-04, with the labels that each got.

#938 達成方法集 F97 の翻訳
  techniques/failures/F97.html
  techniques/index.html
Labels: 達成方法集-201910

#939 達成方法集 F98 の翻訳
  techniques/failures/F98.html
  techniques/index.html
Labels: 達成方法集-201910

#940 達成方法集 F102 の翻訳
  techniques/failures/F102.html
  techniques/index.html
Labels: 達成方法集-201910

#941 達成方法集 F101 の翻訳
  techniques/failures/F101.html
  techniques/index.html
Labels: 達成方法集-201910

#943 SRC39の翻訳
  techniques/client-side-script/SCR39.html
Labels: 達成方法集-201910

#934 C39 の翻訳
  techniques/css/C39.html
  techniques/index.html
  understanding/animation-from-interactions.html
Labels: 達成方法集-201910

#942 C40の翻訳
  techniques/css/C40.html
  techniques/index.html
Labels: 達成方法集-201910

#922 解説書：達成基準2.5.1の更新
  understanding/pointer-gestures.html
Labels: 解説書-v2

#946 SC 3.3.4深刻な結果→重大な結果
  understanding/error-prevention-legal-financial-data.html
Labels: 解説書-v2

#952 work-stepの更新
  work-step.md
  work-step_split.md
Labels: 達成方法集-201910

#926 G157置換作業（Issue 489 ）
  techniques/general/G157.html
Labels: 置換レビュー済み, 達成方法集-201910

#927 G158置換作業（Issue 490 ）
  techniques/general/G158.html
Labels: 置換レビュー済み, 達成方法集-201910

#928 G159置換作業（Issue 491 ）
  techniques/general/G159.html
Labels: 置換レビュー済み, 達成方法集-201910

#929 G160置換作業（Issue 492 ）
  techniques/general/G160.html
Labels: 置換レビュー済み, 達成方法集-201910

#931 G161置換作業（Issue 493 ）
  techniques/general/G161.html
Labels: 置換作業済み, 達成方法集-201910

#953 達成方法集タイトルの更新
  techniques/general/G161.html
  techniques/index.html
Labels: 達成方法集-201910
