Repository waic/wcag21, pull requests merged in 2021-06, with the labels that each got.

#967 達成方法集 ARIA18 の翻訳（Issue695）
  techniques/aria/ARIA18.html
  techniques/index.html
Labels: 置換作業済み, 達成方法集-201910

#962 達成方法ARIA7の翻訳
  techniques/.DS_Store
  techniques/aria/ARIA7.html
  techniques/index.html
Labels: 達成方法集-201910

#966 達成方法集 ARIA19 の翻訳（Issue696）
  techniques/aria/ARIA19.html
  techniques/index.html
Labels: 置換作業済み, 達成方法集-201910

#968 達成方法集 ARIA17 の翻訳（Issue694）
  techniques/aria/ARIA17.html
  techniques/index.html
Labels: 置換作業済み, 達成方法集-201910

#970 達成方法集 ARIA15 の翻訳
  techniques/aria/ARIA15.html
  techniques/index.html
Labels: 達成方法集-201910

#971 達成方法集 ARIA6 の翻訳
  techniques/aria/ARIA6.html
Labels: 置換作業済み, 達成方法集-201910

#972 達成方法集 ARIA14 の翻訳
  techniques/aria/ARIA14.html
  techniques/index.html
Labels: 達成方法集-201910

#973 達成方法集 ARIA16 の翻訳（Issue693）
  techniques/aria/ARIA16.html
  techniques/index.html
Labels: 置換作業済み, 達成方法集-201910

#974 達成方法集 H2 の翻訳
  techniques/html/H2.html
  techniques/index.html
Labels: 達成方法集-201910

#975 達成方法集 H24 の翻訳
  techniques/html/H24.html
  techniques/index.html
Labels: 達成方法集-201910

#976 達成方法集 H25 の翻訳
  techniques/html/H25.html
  techniques/index.html
Labels: 達成方法集-201910

#977 達成方法集 H28 の翻訳
  techniques/html/H28.html
  techniques/index.html
Labels: 達成方法集-201910

#978 達成方法集 H30 の翻訳
  techniques/html/H30.html
  techniques/index.html
Labels: 達成方法集-201910

#979 達成方法集 H32 の翻訳
  techniques/html/H32.html
  techniques/index.html
Labels: 達成方法集-201910

#980 達成方法集 H33 の翻訳
  techniques/html/H33.html
  techniques/index.html
Labels: 達成方法集-201910

#981 達成方法集 H34の翻訳
  techniques/html/H34.html
  techniques/index.html
Labels: 達成方法集-201910

#983 達成方法集 H35の翻訳
  techniques/html/H35.html
  techniques/index.html
Labels: 達成方法集-201910

#984 達成方法集 H36の翻訳
  techniques/html/H36.html
  techniques/index.html
Labels: 達成方法集-201910

#985 ARIA11の作業を実施しました。
  techniques/aria/ARIA11.html
  techniques/index.html
Labels: 達成方法集-201910

#986 ARIA12の作業を実施しました。
  techniques/aria/ARIA12.html
  techniques/index.html
Labels: 達成方法集-201910

#988 H40の作業をしました。
  techniques/html/H40.html
  techniques/index.html
Labels: 達成方法集-201910

#989 H42を作業しました。
  techniques/html/H42.html
  techniques/index.html
Labels: 達成方法集-201910

#990 H43を作業しました。
  techniques/html/H43.html
  techniques/index.html
Labels: 達成方法集-201910

#993 達成方法集 H96の翻訳
  techniques/html/H96.html
  techniques/index.html
Labels: 達成方法集-201910

#991 H44を作業しました。
  techniques/html/H44.html
  techniques/index.html
Labels: 達成方法集-201910

#992 達成方法集 H97の翻訳
  techniques/html/H97.html
  techniques/index.html
Labels: 達成方法集-201910

#997 達成方法集 H94の翻訳
  techniques/html/H94.html
  techniques/index.html
Labels: 達成方法集-201910

#998 達成方法集 H93の翻訳
  techniques/html/H93.html
  techniques/index.html
Labels: 達成方法集-201910

#999 Update H70.html
  techniques/html/H70.html
Labels: 達成方法集-201910

#1000 Update H39.html
  techniques/html/H39.html
Labels: 達成方法集-201910

#995 解説書2.4.6の更新
  understanding/headings-and-labels.html
Labels: 解説書-v2

#1005 タイトルの修正
  techniques/index.html
Labels: 達成方法集-201910

#1002 達成方法集 H85の翻訳
  techniques/html/H85.html
  techniques/index.html
Labels: 達成方法集-201910

#1006 H45の作業をしました。
  techniques/html/H45.html
  techniques/index.html
Labels: 達成方法集-201910

#1007 H46の作業をしました
  techniques/html/H46.html
  techniques/index.html
Labels: 達成方法集-201910

#1013 ARIA11の原文にない記述を削除
  techniques/aria/ARIA11.html
Labels: 達成方法集-201910
