Repository waic/wcag21, pull requests merged in 2022-03, with the labels that each got.

#1324 G177を作業しました
  techniques/general/G177.html
  techniques/index.html
Labels: 達成方法集-201910

#1325 G178の作業をしました。
  techniques/general/G178.html
  techniques/index.html
Labels: 達成方法集-201910

#1306 達成基準 1.4.13 の修正
  guidelines/index.html
  understanding/content-on-hover-or-focus.html
Labels: WCAG21, 解説書-v3

#1307 5.3.1 適合表明 の修正
  guidelines/index.html
Labels: WCAG21

#1319 「7. ユーザインタフェース コンポーネントの入力目的」表記ゆれなどの修正
  guidelines/index.html
Labels: WCAG21

#1308 用語集「キャプション」翻訳の修正
  guidelines/index.html
Labels: WCAG21

#1309 用語集における「need to」の翻訳修正
  guidelines/index.html
Labels: WCAG21

#1312 達成基準 2.5.2 を理解する: 誤字修正「ダウインイベント」→「ダウンイベント」
  understanding/pointer-cancellation.html
Labels: 解説書-v3

#1311 2.5.3 &times; 記号の誤記修正
  understanding/label-in-name.html
Labels: 解説書-v3

#1313 解説書 SC 3.3.1 注記のリンクラベル修正
  understanding/error-identification.html
Labels: 解説書-v3

#1316 達成方法集 F101 の誤字修正
  techniques/failures/F101.html
Labels: 達成方法集-201910

#1317 解説書 SC 3.1.5 の誤記修正
  understanding/reading-level.html
Labels: 解説書-v3

#1318 解説書 SC 1.4.1 訳注のリンク切れ修正
  understanding/use-of-color.html
Labels: 解説書-v3

#1320 達成基準 1.4.13 修正
  guidelines/index.html
  understanding/content-on-hover-or-focus.html
Labels: 解説書-v3

#1322 G175の作業を実施しました。
  techniques/general/G175.html
  techniques/index.html
Labels: 達成方法集-201910

#1323 G176の作業を実施しました。
  techniques/general/G176.html
  techniques/index.html
Labels: 達成方法集-201910

#1326 G175修正反映しました。
  techniques/general/G175.html
Labels: 達成方法集-201910

#1327 G112 : 事例3の、誤解を招くカッコ書きの解消
  techniques/general/G112.html
Labels: 達成方法集-201910

#1331 解説書 1.4.3 および 1.4.6 の修正
  understanding/contrast-enhanced.html
  understanding/contrast-minimum.html
Labels: 解説書-v3

#1328 解説書1.4.12 : 図のキャプション修正
  understanding/text-spacing.html
Labels: 解説書-v3

#1329 解説書 2.1.4 および達成方法集 F99 の誤記修正
  techniques/failures/F99.html
  understanding/character-key-shortcuts.html
Labels: 達成方法集-201910, 解説書-v3

#1330 「短いテキストによる代替」「簡潔なテキストによる代替」の表記ゆれ解消
  techniques/aria/ARIA15.html
  techniques/general/G100.html
  techniques/general/G68.html
  techniques/general/G73.html
  techniques/general/G74.html
  techniques/general/G92.html
  techniques/general/G95.html
  techniques/html/H37.html
  techniques/html/H45.html
  techniques/index.html
  understanding/non-text-content.html
Labels: 達成方法集-201910, 解説書-v3

#1333 working example の訳を「動作例」で統一
  techniques/aria/ARIA1.html
  techniques/aria/ARIA10.html
  techniques/aria/ARIA14.html
  techniques/aria/ARIA17.html
  techniques/aria/ARIA18.html
  techniques/aria/ARIA19.html
  techniques/aria/ARIA22.html
  techniques/aria/ARIA23.html
  techniques/aria/ARIA4.html
  techniques/aria/ARIA5.html
  techniques/aria/ARIA9.html
  techniques/client-side-script/SCR14.html
  techniques/client-side-script/SCR18.html
  techniques/client-side-script/SCR19.html
  techniques/client-side-script/SCR29.html
  techniques/client-side-script/SCR30.html
  techniques/client-side-script/SCR33.html
  techniques/client-side-script/SCR35.html
  techniques/client-side-script/SCR39.html
  techniques/css/C31.html
  techniques/css/C32.html
  techniques/css/C33.html
  techniques/css/C39.html
  techniques/css/C40.html
  techniques/failures/F100.html
  techniques/failures/F106.html
  techniques/failures/F90.html
  techniques/general/G175.html
  techniques/general/G65.html
Labels: 達成方法集-201910
