Repository waic/wcag21, pull requests merged in 2022-04, with the labels that each got.

#1348 達成方法集 H42 の修正
  techniques/html/H42.html
Labels: 達成方法集-201910

#1349 context-sensitive help の和訳修正
  guidelines/index.html
  techniques/general/G200.html
  understanding/help.html
Labels: 達成方法集-201910, WCAG21, 解説書-v3

#1357 達成方法集 T1の翻訳
  techniques/index.html
  techniques/text/T1.html
Labels: 達成方法集-201910

#1358 達成方法集 T2の翻訳
  techniques/index.html
  techniques/text/T2.html
Labels: 達成方法集-201910

#1359 達成方法集 T3の翻訳
  techniques/index.html
  techniques/text/T3.html
Labels: 達成方法集-201910, don't yet merge

#1360 達成方法集 SVR1の翻訳
  techniques/index.html
  techniques/server-side-script/SVR1.html
Labels: 達成方法集-201910

#1361 達成方法集 SVR2の翻訳
  techniques/index.html
  techniques/server-side-script/SVR2.html
Labels: 達成方法集-201910, don't yet merge

#1362 達成方法集 SVR3の翻訳
  techniques/index.html
  techniques/server-side-script/SVR3.html
Labels: 達成方法集-201910

#1363 達成方法集 SVR4の翻訳
  techniques/index.html
  techniques/server-side-script/SVR4.html
Labels: 達成方法集-201910

#1314 達成方法集 SM14の翻訳 達成方法集
  techniques/index.html
  techniques/smil/SM14.html
Labels: 達成方法集-201910

#1366 達成方法集 SM2の翻訳
  techniques/index.html
  techniques/smil/SM2.html
Labels: 達成方法集-201910

#1372 達成方法集 SM7の翻訳
  techniques/index.html
  techniques/smil/SM7.html
Labels: 達成方法集-201910

#1365 達成方法集 SM1の翻訳
  techniques/index.html
  techniques/smil/SM1.html
Labels: 達成方法集-201910

#1335 達成方法集 PDF22の翻訳
  techniques/index.html
  techniques/pdf/PDF22.html
Labels: 達成方法集-201910, don't yet merge
