Repository waic/wcag21, pull requests merged in 2023-07, with the labels that each got.

#1781 WCAG 2.1解説書（2022年9月版更新）：3.3.4: エラー回避 (法的、金融、データ)
  understanding/error-prevention-legal-financial-data.html
Labels: 解説書-v4-202210

#1782 WCAG 2.1解説書（2022年9月版更新）：3.3.5: ヘルプ
  understanding/help.html
Labels: 解説書-v4-202210

#1784 WCAG 2.1解説書（2022年9月版更新）：4.1: 互換性
  understanding/compatible.html
Labels: 解説書-v4-202210

#1783 WCAG 2.1解説書（2022年9月版更新）：3.3.6: エラー回避 (すべて)
  understanding/error-prevention-all.html
Labels: 解説書-v4-202210

#1785 WCAG 2.1解説書（2022年9月版更新）：4.1.2: 名前 (name) ・役割 (role) 及び値 (value)
  understanding/name-role-value.html
Labels: 解説書-v4-202210

#1786 WCAG 2.1解説書（2022年9月版更新）：4.1.3: ステータスメッセージ
  understanding/status-messages.html
Labels: 解説書-v4-202210

#1779 用語集：コンテンツ (ウェブコンテンツ)の修正
  guidelines/index.html
  understanding/change-on-request.html
  understanding/headings-and-labels.html
  understanding/info-and-relationships.html
  understanding/label-in-name.html
  understanding/link-purpose-in-context.html
  understanding/non-text-content.html
  understanding/non-text-contrast.html
  understanding/on-focus.html
  understanding/on-input.html
  understanding/reading-level.html
Labels: WCAG21, 解説書-v4-202210

#1798 WCAG 2.1解説書（2022年9月版更新）：メタデータを理解する
  understanding/understanding-metadata.html
Labels: 解説書-v4-202210

#1797 WCAG 2.1解説書（2022年9月版更新）：ウェブコンテンツ技術の使用法のアクセシビリティサポートを文書化する
  understanding/documenting-accessibility-support.html
Labels: 解説書-v4-202210

#1776 WCAG 2.1解説書（2022年9月版更新）：3.3.2: ラベル又は説明
  understanding/labels-or-instructions.html
Labels: 解説書-v4-202210

#1796 WCAG 2.1解説書（2022年9月版更新）：他の文書からの WCAG 2.1 の参照方法
  understanding/documenting-accessibility-support.html
  understanding/index.html
  understanding/refer-to-wcag.html
Labels: 解説書-v4-202210

#1780 用語集：適合している代替版の修正
  guidelines/index.html
  understanding/conformance.html
  understanding/link-purpose-in-context.html
Labels: WCAG21, 解説書-v4-202210

#1789 用語集：慣用句の修正
  guidelines/index.html
  understanding/unusual-words.html
Labels: WCAG21, 解説書-v4-202210

#1791 用語集：プログラムによる解釈が可能なリンクのコンテキストの修正
  guidelines/index.html
  understanding/link-purpose-in-context.html
Labels: WCAG21, 解説書-v4-202210

#1792 用語集：手話通訳の修正
  guidelines/index.html
  understanding/sign-language-prerecorded.html
Labels: WCAG21, 解説書-v4-202210

#1793 用語集：状態の修正
  guidelines/index.html
  understanding/non-text-contrast.html
Labels: WCAG21, 解説書-v4-202210

#1795 用語集：ターゲットの修正
  guidelines/index.html
  understanding/target-size.html
Labels: WCAG21, 解説書-v4-202210

#1801 「正しく読むシーケンス」「意味のあるシーケンス」への置換
  guidelines/index.html
  techniques/css/C27.html
  techniques/css/C6.html
  techniques/css/C8.html
  techniques/failures/F1.html
  techniques/failures/F32.html
  techniques/failures/F33.html
  techniques/failures/F34.html
  techniques/failures/F49.html
  techniques/general/G57.html
  techniques/general/G59.html
  techniques/html/H34.html
  techniques/html/H56.html
  techniques/index.html
  techniques/pdf/PDF3.html
  understanding/adaptable.html
  understanding/info-and-relationships.html
  understanding/meaningful-sequence.html
  understanding/sensory-characteristics.html
Labels: 達成方法集-201910, WCAG21, 解説書-v4-202210

#1803 用語集 : コンテキストの変化 (changes of context) の修正
  understanding/change-on-request.html
  understanding/on-focus.html
  understanding/on-input.html
  understanding/status-messages.html
Labels: 解説書-v4-202210

#1787 用語集：支援技術の修正
  guidelines/index.html
  understanding/abbreviations.html
  understanding/audio-control.html
  understanding/bypass-blocks.html
  understanding/captions-live.html
  understanding/captions-prerecorded.html
  understanding/change-on-request.html
  understanding/character-key-shortcuts.html
  understanding/consistent-identification.html
  understanding/consistent-navigation.html
  understanding/content-on-hover-or-focus.html
  understanding/contrast-enhanced.html
  understanding/contrast-minimum.html
  understanding/focus-order.html
  understanding/headings-and-labels.html
  understanding/identify-input-purpose.html
  understanding/identify-purpose.html
  understanding/images-of-text-no-exception.html
  understanding/images-of-text.html
  understanding/info-and-relationships.html
  understanding/label-in-name.html
  understanding/language-of-page.html
  understanding/language-of-parts.html
  understanding/link-purpose-in-context.html
  understanding/link-purpose-link-only.html
  understanding/location.html
  understanding/meaningful-sequence.html
  understanding/media-alternative-prerecorded.html
  understanding/motion-actuation.html
  understanding/multiple-ways.html
  understanding/name-role-value.html
  understanding/non-text-content.html
  understanding/non-text-contrast.html
  understanding/on-focus.html
  understanding/on-input.html
  understanding/page-titled.html
  understanding/pointer-cancellation.html
  understanding/pronunciation.html
  understanding/reading-level.html
  understanding/resize-text.html
  understanding/status-messages.html
  understanding/text-alternatives.html
  understanding/text-spacing.html
  understanding/three-flashes-or-below-threshold.html
  understanding/three-flashes.html
  understanding/unusual-words.html
  understanding/visual-presentation.html
Labels: WCAG21, 解説書-v4-202210

#1770 用語集：ダウンイベントの修正
  guidelines/index.html
  understanding/pointer-cancellation.html
Labels: WCAG21, 解説書-v4-202210

#1794 スタイルプロパティの修正
  guidelines/index.html
  understanding/text-spacing.html
Labels: WCAG21, 解説書-v4-202210
