Repository waic/wcag21, pull requests merged in 2023-01, with the labels that each got.

#1549 WCAG 2.1解説書（2022年9月版更新）：イントロダクション
  understanding/intro.html
Labels: 解説書-v4-202210

#1550 WCAG 2.1解説書（2022年9月版更新）：WCAG 達成基準の達成方法を理解する
  understanding/understanding-techniques.html
Labels: 解説書-v4-202210

#1551 WCAG 2.1解説書（2022年9月版更新）：ACT ルールを理解する
  understanding/understanding-act-rules.html
Labels: 解説書-v4-202210

#1552 WCAG 2.1解説書（2022年9月版更新）：1.1: テキストによる代替
  understanding/text-alternatives.html
Labels: 解説書-v4-202210

#1553 WCAG 2.1解説書（2022年9月版更新）：1.1.1: 非テキストコンテンツを理解する
  understanding/non-text-content.html
Labels: 解説書-v4-202210

#1555 WCAG 2.1解説書（2022年9月版更新）：1.2: 時間依存メディア
  understanding/time-based-media.html
Labels: 解説書-v4-202210

#1557 WCAG 2.1解説書（2022年9月版更新）：1.2.2: キャプション (収録済)
  understanding/captions-prerecorded.html
Labels: 解説書-v4-202210

#1558 WCAG 2.1解説書（2022年9月版更新）：1.2.3: 音声解説、又はメディアに対する代替 (収録済)
  understanding/audio-description-or-media-alternative-prerecorded.html
Labels: 解説書-v4-202210

#1559 WCAG 2.1解説書（2022年9月版更新）：1.2.4: キャプション (ライブ)
  understanding/captions-live.html
Labels: 解説書-v4-202210

#1560 WCAG 2.1解説書（2022年9月版更新）：1.2.5: 音声解説 (収録済)
  understanding/audio-description-prerecorded.html
Labels: 解説書-v4-202210

#1561 WCAG 2.1解説書（2022年9月版更新）：1.2.6: 手話 (収録済)
  understanding/sign-language-prerecorded.html
Labels: 解説書-v4-202210

#1562 WCAG 2.1解説書（2022年9月版更新）：1.2.7: 拡張音声解説 (収録済)
  understanding/extended-audio-description-prerecorded.html
Labels: 解説書-v4-202210

#1563 WCAG 2.1解説書（2022年9月版更新）：1.2.8: メディアに対する代替 (収録済)
  understanding/media-alternative-prerecorded.html
Labels: 解説書-v4-202210

#1564 WCAG 2.1解説書（2022年9月版更新）：1.2.9: 音声のみ (ライブ)
  understanding/audio-only-live.html
Labels: 解説書-v4-202210

#1565 WCAG 2.1解説書（2022年9月版更新）：1.3: 適応可能
  understanding/adaptable.html
Labels: 解説書-v4-202210

#1566 WCAG 2.1解説書（2022年9月版更新）：1.3.1: 情報及び関係性
  understanding/info-and-relationships.html
Labels: 解説書-v4-202210

#1567 WCAG 2.1解説書（2022年9月版更新）：1.3.2: 意味のある順序
  understanding/meaningful-sequence.html
Labels: 解説書-v4-202210

#1569 WCAG 2.1解説書（2022年9月版更新）：1.3.4: 表示の向き
  understanding/orientation.html
Labels: 解説書-v4-202210

#1570 WCAG 2.1解説書（2022年9月版更新）：1.3.5: 入力目的の特定
  understanding/identify-input-purpose.html
Labels: 解説書-v4-202210

#1571 WCAG 2.1解説書（2022年9月版更新）：1.3.6: 目的の特定
  understanding/identify-purpose.html
Labels: 解説書-v4-202210

#1573 WCAG 2.1解説書（2022年9月版更新）：1.4: 判別可能
  understanding/distinguishable.html
Labels: 解説書-v4-202210

#1533 SC 4.1.1 2022-09-02版更新
  understanding/parsing.html
Labels: 解説書-v4-202210

#1540 エラー回避→誤り防止
  guidelines/index.html
  techniques/client-side-script/SCR18.html
  techniques/general/G155.html
  techniques/general/G164.html
  techniques/general/G168.html
  techniques/general/G199.html
  techniques/general/G98.html
  techniques/general/G99.html
  understanding/error-prevention-all.html
  understanding/error-prevention-legal-financial-data.html
  understanding/error-suggestion.html
  understanding/help.html
  understanding/index.html
  understanding/input-assistance.html
  understanding/parsing.html
Labels: 達成方法集-201910, WCAG21, 解説書-v3

#1543 解説書1.4.13 非表示にすることができる 文修正
  understanding/content-on-hover-or-focus.html
Labels: 解説書-v3

#1554 用語集：音声解説の注記4の脱字
  guidelines/index.html
Labels: WCAG21

#1542 G58の修正
  techniques/general/G151.html
  techniques/general/G157.html
  techniques/general/G58.html
  techniques/general/G69.html
  techniques/index.html
  understanding/audio-description-or-media-alternative-prerecorded.html
  understanding/media-alternative-prerecorded.html
Labels: 達成方法集-201910, 解説書-v3
