Repository waic/wcag21, pull requests merged in 2023-04, with the labels that each got.

#1661 解説書4.1.3「意図」の修正
  understanding/status-messages.html
Labels: 解説書-v4-202210

#1658 WCAG 2.1解説書（2022年9月版更新）：2.5.4: 動きによる起動
  understanding/motion-actuation.html
Labels: 解説書-v4-202210, WAICレビュー

#1659 解説書1.4.10 参考達成方法への修正
  understanding/reflow.html
Labels: 解説書-v4-202210

#1663 WCAG 2.1解説書（2022年9月版更新）：1.4.8: 視覚的提示
  understanding/visual-presentation.html
Labels: 解説書-v4-202210

#1664 WCAG 2.1解説書（2022年9月版更新）：1.4.9: 文字画像 (例外なし)
  understanding/images-of-text-no-exception.html
Labels: 解説書-v4-202210

#1668 用語集：閃光の修正
  guidelines/index.html
  understanding/three-flashes-or-below-threshold.html
  understanding/three-flashes.html
Labels: WCAG21

#1665 WCAG 2.1解説書（2022年9月版更新）：1.4.10: リフロー
  understanding/reflow.html
Labels: 解説書-v4-202210

#1670 WCAG 2.1解説書（2022年9月版更新）：1.4.13: ホバー又はフォーカスで表示されるコンテンツ
  understanding/content-on-hover-or-focus.html
Labels: 解説書-v4-202210

#1671 WCAG 2.1解説書（2022年9月版更新）：2.1: キーボード操作可能
  understanding/keyboard-accessible.html
Labels: 解説書-v4-202210

#1675 WCAG 2.1解説書（2022年9月版更新）：2.2: 十分な時間
  understanding/enough-time.html
Labels: 解説書-v4-202210

#1673 WCAG 2.1解説書（2022年9月版更新）：2.1.3: キーボード (例外なし)
  understanding/keyboard-no-exception.html
Labels: 解説書-v4-202210

#1674 WCAG 2.1解説書（2022年9月版更新）：2.1.4: 文字キーのショートカット
  understanding/character-key-shortcuts.html
Labels: 解説書-v4-202210

#1666 WCAG 2.1解説書（2022年9月版更新）：1.4.11: 非テキストのコントラスト
  understanding/img/ntc-focus-background.png
  understanding/img/ntc-focus-border.png
  understanding/img/ntc-focus-inner-border.png
  understanding/img/ntc-focus-inner-outer.png
  understanding/img/ntc-focus-inner-white.png
  understanding/img/ntc-focus-inner.png
  understanding/img/ntc-focus-outer-green.png
  understanding/img/ntc-focus-outer-yellow.png
  understanding/non-text-contrast.html
Labels: 解説書-v4-202210

#1677 達成基準2.5.3を「ラベルを含む名前 (name)」に変更
  guidelines/index.html
  techniques/failures/F96.html
  techniques/general/G208.html
  techniques/general/G211.html
  understanding/index.html
  understanding/input-modalities.html
  understanding/label-in-name.html
  understanding/motion-actuation.html
  understanding/pointer-cancellation.html
Labels: 達成方法集-201910, WCAG21, 解説書-v4-202210

#1688 WCAG 2.1解説書（2022年9月版更新）：2.2.2: 一時停止、停止、非表示
  understanding/pause-stop-hide.html
Labels: 解説書-v4-202210

#1689 WCAG 2.1解説書（2022年9月版更新）：2.2.3: タイミング非依存
  understanding/no-timing.html
Labels: 解説書-v4-202210

#1690 WCAG 2.1解説書（2022年9月版更新）：2.2.4: 割り込み
  understanding/interruptions.html
Labels: 解説書-v4-202210

#1691 WCAG 2.1解説書（2022年9月版更新）：2.2.5: 再認証
  understanding/re-authenticating.html
Labels: 解説書-v4-202210

#1693 WCAG 2.1解説書（2022年9月版更新）：2.3: 発作と身体的反応
  understanding/seizures-and-physical-reactions.html
Labels: 解説書-v4-202210

#1695 WCAG 2.1解説書（2022年9月版更新）：2.3.2: 3 回の閃光
  understanding/three-flashes.html
Labels: 解説書-v4-202210

#1686 達成基準 4.1.2を「名前 (name)・役割 (role)・値 (value)」に変更
  guidelines/index.html
  techniques/aria/ARIA14.html
  techniques/aria/ARIA16.html
  techniques/aria/ARIA4.html
  techniques/aria/ARIA5.html
  techniques/failures/F15.html
  techniques/failures/F20.html
  techniques/failures/F59.html
  techniques/failures/F68.html
  techniques/failures/F79.html
  techniques/failures/F86.html
  techniques/failures/F89.html
  techniques/general/G10.html
  techniques/general/G108.html
  techniques/general/G135.html
  techniques/html/H44.html
  techniques/html/H64.html
  techniques/html/H65.html
  techniques/html/H88.html
  techniques/html/H91.html
  techniques/pdf/PDF10.html
  techniques/pdf/PDF12.html
  understanding/compatible.html
  understanding/headings-and-labels.html
  understanding/index.html
  understanding/labels-or-instructions.html
  understanding/name-role-value.html
  understanding/parsing.html
  understanding/status-messages.html
  understanding/use-of-color.html
Labels: 達成方法集-201910, WCAG21, 解説書-v4-202210

#1697 WCAG 2.1解説書（2022年9月版更新）：2.4: ナビゲーション可能
  understanding/navigable.html
Labels: 解説書-v4-202210

#1698 WCAG 2.1解説書（2022年9月版更新）：2.4.1: ブロックスキップ
  understanding/bypass-blocks.html
Labels: 解説書-v4-202210
