Repository waic/wcag21, pull requests merged in 2023-03, with the labels that each got.

#1617 4.1.2終了タグの修正
  understanding/name-role-value.html
Labels: 達成方法集-201910

#1545 用語集：略語の修正提案
  guidelines/index.html
  understanding/abbreviations.html
Labels: WCAG21, 解説書-v4-202210

#1572 用語集：必要不可欠の修正
  guidelines/index.html
  understanding/animation-from-interactions.html
  understanding/concurrent-input-mechanisms.html
  understanding/images-of-text-no-exception.html
  understanding/images-of-text.html
  understanding/motion-actuation.html
  understanding/no-timing.html
  understanding/non-text-contrast.html
  understanding/orientation.html
  understanding/pause-stop-hide.html
  understanding/pointer-cancellation.html
  understanding/pointer-gestures.html
  understanding/target-size.html
  understanding/timing-adjustable.html
Labels: WCAG21, 解説書-v4-202210

#1578 a couple の訳を「２、３の」から「いくつかの」に変更
  guidelines/index.html
Labels: WCAG21

#1632 G156 助詞の修正
  techniques/general/G156.html
Labels: 達成方法集-201910, public-comment

#1633 H34 衍字の修正
  techniques/html/H34.html
Labels: 達成方法集-201910, public-comment

#1634 G111 脱字の修正
  techniques/general/G111.html
Labels: 達成方法集-201910, public-comment

#1620 2023-03 WAICレビューコメント対応：解説書1.4.11のリンクと要素を修正
  understanding/non-text-contrast.html
Labels: 解説書-v4-202210, WAICレビュー

#1635 衍字の修正
  techniques/failures/F34.html
  techniques/general/G152.html
  understanding/pointer-gestures.html
Labels: 達成方法集-201910, 解説書-v4-202210, WAICレビュー

#1636 ドラッグ＆ドロップに統一
  understanding/input-modalities.html
  understanding/pointer-cancellation.html
Labels: 解説書-v4-202210, WAICレビュー

#1639 テスターに統一
  techniques/general/G217.html
Labels: 達成方法集-201910, WAICレビュー

#1637 コロン直後のスペースを挿入
  techniques/general/G134.html
  techniques/general/G138.html
  techniques/general/G158.html
  techniques/general/G159.html
  techniques/general/G89.html
  understanding/character-key-shortcuts.html
  understanding/content-on-hover-or-focus.html
  understanding/non-text-contrast.html
  understanding/sign-language-prerecorded.html
Labels: 達成方法集-201910, 解説書-v4-202210, WAICレビュー

#1642 約物の直後に全角スペースの挿入
  techniques/general/G168.html
  techniques/general/G211.html
  understanding/animation-from-interactions.html
  understanding/conformance.html
Labels: 達成方法集-201910, 解説書-v4-202210, WAICレビュー

#1544 and/orの「及び／又は」への修正
  guidelines/index.html
  understanding/audio-description-or-media-alternative-prerecorded.html
  understanding/audio-description-prerecorded.html
  understanding/captions-live.html
  understanding/captions-prerecorded.html
  understanding/extended-audio-description-prerecorded.html
  understanding/media-alternative-prerecorded.html
  understanding/no-timing.html
  understanding/sign-language-prerecorded.html
Labels: WCAG21, 解説書-v3

#1644 解説書2.5.1 代替テキストの改善
  understanding/pointer-gestures.html
Labels: 解説書-v4-202210, WAICレビュー

#1646 解説書2.5.2ダウンイベントの修正
  understanding/pointer-cancellation.html
Labels: 解説書-v4-202210, WAICレビュー

#1648 解説書2.4.4 事例 二重かぎ括弧の削除
  understanding/link-purpose-in-context.html
Labels: 解説書-v4-202210, WAICレビュー

#1649 G215/G216の翻訳を揃えた
  techniques/general/G215.html
  techniques/general/G216.html
Labels: 達成方法集-201910, WAICレビュー

#1651 H98解説 第2段落対応
  techniques/html/H98.html
Labels: 達成方法集-201910, public-comment

#1655 2.5.3 ペルソナの心の声 更新
  understanding/animation-from-interactions.html
Labels: 解説書-v4-202210

#1656 解説書1.3.5 意図 第1段落の修正
  understanding/identify-input-purpose.html
Labels: public-comment, 解説書-v4-202210

#1575 用語集：ラベル 注記の修正
  guidelines/index.html
  understanding/headings-and-labels.html
  understanding/label-in-name.html
  understanding/labels-or-instructions.html
  understanding/non-text-content.html
Labels: WCAG21, 解説書-v4-202210

#1579 用語集：拡張音声解説の注記の修正
  guidelines/index.html
  understanding/audio-description-or-media-alternative-prerecorded.html
  understanding/audio-description-prerecorded.html
  understanding/captions-live.html
  understanding/captions-prerecorded.html
  understanding/extended-audio-description-prerecorded.html
  understanding/media-alternative-prerecorded.html
Labels: WCAG21, 解説書-v4-202210

#1638 WCAG 2.1解説書（2022年9月版更新）：1.4.3: コントラスト (最低限)
  understanding/contrast-minimum.html
Labels: 解説書-v4-202210

#1640 WCAG 2.1解説書（2022年9月版更新）：1.4.4: テキストのサイズ変更
  understanding/resize-text.html
Labels: 解説書-v4-202210

#1641 WCAG 2.1解説書（2022年9月版更新）：1.4.5: 文字画像
  understanding/images-of-text.html
Labels: 解説書-v4-202210

#1643 WCAG 2.1解説書（2022年9月版更新）：1.4.6: コントラスト (高度)
  understanding/contrast-enhanced.html
Labels: 解説書-v4-202210

#1654 文言の調整（入力メカニズム非依存→入力メカニズムの共存）：WCAG 2.1解説書 目次 & 2.5.6
  guidelines/index.html
  techniques/failures/F98.html
  understanding/concurrent-input-mechanisms.html
  understanding/index.html
  understanding/input-modalities.html
  understanding/language-of-page.html
  understanding/target-size.html
Labels: 達成方法集-201910, WCAG21, 解説書-v4-202210

#1657 WCAG 2.1解説書（2022年9月版更新）：1.4.12: テキストの間隔
  understanding/img/spacing_cutoff_fail_horizontal.png
  understanding/img/spacing_cutoff_fail_vertical.png
  understanding/img/spacing_overlap_fail.png
  understanding/text-spacing.html
Labels: 解説書-v4-202210, WAICレビュー
