Repository waic/wcag21, pull requests merged in 2023-05, with the labels that each got.

#1699 G208 翻訳を修正して訳注を追加
  techniques/general/G208.html
Labels: 達成方法集-201910

#1700 適合を理解する：リンクをWCAG 2.0解説書に基づき修正
  understanding/conformance.html
Labels: 解説書-v4-202210

#1713 WCAG 2.1解説書（2022年9月版更新）：2.4.2: ページタイトル
  understanding/page-titled.html
Labels: 解説書-v4-202210

#1714 WCAG 2.1解説書（2022年9月版更新）：2.4.3: フォーカス順序
  understanding/focus-order.html
Labels: 解説書-v4-202210

#1715 WCAG 2.1解説書（2022年9月版更新）：2.4.4: リンクの目的 (コンテキスト内)
  understanding/link-purpose-in-context.html
Labels: 解説書-v4-202210

#1701 用語集：ステータスメッセージの修正
  guidelines/index.html
  understanding/status-messages.html
Labels: WCAG21, 解説書-v4-202210

#1702 用語集：手話の修正
  guidelines/index.html
  understanding/captions-live.html
  understanding/captions-prerecorded.html
  understanding/contrast-enhanced.html
  understanding/contrast-minimum.html
  understanding/images-of-text-no-exception.html
  understanding/images-of-text.html
  understanding/media-alternative-prerecorded.html
  understanding/motion-actuation.html
  understanding/non-text-content.html
  understanding/resize-text.html
  understanding/sign-language-prerecorded.html
  understanding/text-alternatives.html
  understanding/text-spacing.html
Labels: WCAG21, 解説書-v4-202210

#1703 用語集：シングルポインタの修正
  guidelines/index.html
  understanding/pointer-cancellation.html
  understanding/pointer-gestures.html
Labels: WCAG21, 解説書-v4-202210

#1704 用語集：状態の修正
  guidelines/index.html
  understanding/non-text-contrast.html
Labels: WCAG21, 解説書-v4-202210

#1705 解説書2.5.1相互作用をインタラクションに修正
  understanding/pointer-gestures.html
Labels: 解説書-v4-202210

#1706 キーボード：「終点だけではない」への変更
  guidelines/index.html
  understanding/keyboard-no-exception.html
  understanding/keyboard.html
Labels: WCAG21, 解説書-v4-202210

#1707 用語集：映像しか含まないの修正
  guidelines/index.html
  understanding/audio-only-and-video-only-prerecorded.html
  understanding/media-alternative-prerecorded.html
Labels: WCAG21, 解説書-v4-202210

#1708 用語集：ユーザエージェントの修正
  guidelines/index.html
  understanding/audio-control.html
  understanding/bypass-blocks.html
  understanding/captions-live.html
  understanding/captions-prerecorded.html
  understanding/character-key-shortcuts.html
  understanding/content-on-hover-or-focus.html
  understanding/contrast-enhanced.html
  understanding/contrast-minimum.html
  understanding/identify-input-purpose.html
  understanding/identify-purpose.html
  understanding/images-of-text-no-exception.html
  understanding/images-of-text.html
  understanding/info-and-relationships.html
  understanding/meaningful-sequence.html
  understanding/media-alternative-prerecorded.html
  understanding/motion-actuation.html
  understanding/name-role-value.html
  understanding/non-text-content.html
  understanding/non-text-contrast.html
  understanding/resize-text.html
  understanding/text-alternatives.html
  understanding/text-spacing.html
  understanding/three-flashes.html
  understanding/visual-presentation.html
Labels: WCAG21, 解説書-v4-202210

#1696 WCAG 2.1解説書（2022年9月版更新）：2.3.3: インタラクションによるアニメーション
  understanding/animation-from-interactions.html
Labels: 解説書-v4-202210, WCAG22-backport?

#1718 wrapの翻訳を「包むこと」から「折り返し」に修正 #1712 WCAG 2.1解説書 1.4.10
  understanding/reflow.html
Labels: WCAG21, 解説書-v4-202210
