Repository waic/wcag21, pull requests merged in 2023-02, with the labels that each got.

#1576 WCAG 2.1解説書（2022年9月版更新）：1.4.2: 音声の制御
  understanding/audio-control.html
Labels: 解説書-v4-202210

#1585 衍字の修正「実際には何も見逃していていないにもかかわらず」
  understanding/non-text-content.html
Labels: public-comment, 解説書-v4-202210

#1586 「デジベル」を「デシベル」に修正
  techniques/general/G56.html
Labels: 達成方法集-201910, public-comment

#1583 重複した助詞の削除「より効率よくコンテンツをを閲覧したり」
  techniques/css/C20.html
Labels: 達成方法集-201910, public-comment

#1577 delete unnecessary space
  guidelines/index.html
Labels: WCAG21

#1598 解説書1.1.1テストへの修正
  understanding/non-text-content.html
Labels: 解説書-v3

#1597 解説書4.1.3の小さな修正
  understanding/status-messages.html
Labels: 解説書-v4-202210

#1596 適用 (対象)への翻訳
  techniques/general/G141.html
  techniques/general/G83.html
  techniques/html/H65.html
Labels: 達成方法集-201910

#1581 ガイドライン1.1：大活字への変更と訳注の追記
  guidelines/index.html
  understanding/text-alternatives.html
Labels: WCAG21, 解説書-v4-202210

#1541 用語集：一般閃光閾値及び赤色閃光閾値の見直し
  guidelines/index.html
  understanding/three-flashes-or-below-threshold.html
Labels: WCAG21, 解説書-v4-202210

#1604 脱字修正「フォンサイズ」→「フォントサイズ」
  techniques/css/C28.html
Labels: 達成方法集-201910

#1609 スペースの置換、不要な文字列の削除
  guidelines/index.html
Labels: WCAG21
