Repository waic/wcag21, pull requests merged in 2023-06, with the labels that each got.

#1694 WCAG 2.1解説書（2022年9月版更新）：2.3.1: 3 回の閃光、又は閾値以下
  understanding/three-flashes-or-below-threshold.html
Labels: 解説書-v4-202210, WCAG22-backport?

#1730 WCAG 2.1解説書（2022年9月版更新）：2.4.5: 複数の手段
  understanding/multiple-ways.html
Labels: 解説書-v4-202210

#1687 WCAG 2.1解説書（2022年9月版更新）：2.2.1: タイミング調整可能
  understanding/timing-adjustable.html
Labels: 解説書-v4-202210

#1733 WCAG 2.1解説書（2022年9月版更新）：2.4.8: 現在位置
  understanding/location.html
Labels: 解説書-v4-202210

#1734 WCAG 2.1解説書（2022年9月版更新）：2.4.9: リンクの目的 (リンクのみ)
  understanding/link-purpose-link-only.html
Labels: 解説書-v4-202210

#1732 WCAG 2.1解説書（2022年9月版更新）：2.4.7: フォーカスの可視化
  understanding/focus-visible.html
Labels: 解説書-v4-202210

#1735 WCAG 2.1解説書（2022年9月版更新）：2.4.10: セクション見出し
  understanding/section-headings.html
Labels: 解説書-v4-202210

#1738 G144/G193「事例」の未訳修正
  techniques/general/G144.html
  techniques/general/G193.html
Labels: 達成方法集-201910

#1739 WCAG 2.1解説書（2022年9月版更新）：2.5.2: ポインタのキャンセル
  understanding/pointer-cancellation.html
Labels: 解説書-v4-202210

#1740 WCAG 2.1解説書（2022年9月版更新）：2.5.3: ラベルを含む名前 (name)
  understanding/label-in-name.html
Labels: 解説書-v4-202210

#1737 WCAG 2.1解説書（2022年9月版更新）：2.5.1: ポインタのジェスチャ
  understanding/pointer-gestures.html
Labels: 解説書-v4-202210

#1747 WCAG 2.1解説書（2022年9月版更新）：3.1: 読み取り可能
  understanding/readable.html
Labels: 解説書-v4-202210

#1748 WCAG 2.1解説書（2022年9月版更新）：3.1.1: ページの言語
  understanding/language-of-page.html
Labels: 解説書-v4-202210

#1744 用語集：ASCII アートの修正
  guidelines/index.html
  understanding/captions-live.html
  understanding/captions-prerecorded.html
  understanding/headings-and-labels.html
  understanding/label-in-name.html
  understanding/media-alternative-prerecorded.html
  understanding/non-text-content.html
  understanding/resize-text.html
Labels: WCAG21, 解説書-v4-202210

#1745 WCAG 2.1解説書（2022年9月版更新）：2.5.5: ターゲットのサイズ
  understanding/target-size.html
Labels: 解説書-v4-202210, WCAG22-backport?

#1749 WCAG 2.1解説書（2022年9月版更新）：3.1.2: 一部分の言語
  understanding/language-of-parts.html
Labels: 解説書-v4-202210

#1752 WCAG 2.1解説書（2022年9月版更新）：3.1.4: 略語
  understanding/abbreviations.html
Labels: 解説書-v4-202210

#1753 WCAG 2.1解説書（2022年9月版更新）：3.1.3: 一般的ではない用語
  understanding/unusual-words.html
Labels: 解説書-v4-202210

#1755 WCAG 2.1解説書（2022年9月版更新）：3.1.6: 発音
  understanding/pronunciation.html
Labels: 解説書-v4-202210

#1756 WCAG 2.1解説書（2022年9月版更新）：3.2: 予測可能
  understanding/predictable.html
Labels: 解説書-v4-202210

#1757 WCAG 2.1解説書（2022年9月版更新）：3.2.1: フォーカス時
  understanding/on-focus.html
Labels: 解説書-v4-202210

#1760 WCAG 2.1解説書（2022年9月版更新）：3.2.3: 一貫したナビゲーション
  understanding/consistent-navigation.html
Labels: 解説書-v4-202210

#1761 WCAG 2.1解説書（2022年9月版更新）：3.2.4: 一貫した識別性
  understanding/consistent-identification.html
Labels: 解説書-v4-202210

#1750 用語集：緊急の修正
  guidelines/index.html
  understanding/interruptions.html
Labels: WCAG21, 解説書-v4-202210

#1751 用語集：自然言語の修正
  guidelines/index.html
  understanding/captions-live.html
  understanding/captions-prerecorded.html
  understanding/contrast-enhanced.html
  understanding/contrast-minimum.html
  understanding/headings-and-labels.html
  understanding/images-of-text-no-exception.html
  understanding/images-of-text.html
  understanding/language-of-page.html
  understanding/language-of-parts.html
  understanding/link-purpose-in-context.html
  understanding/media-alternative-prerecorded.html
  understanding/motion-actuation.html
  understanding/non-text-content.html
  understanding/resize-text.html
  understanding/text-alternatives.html
  understanding/text-spacing.html
Labels: WCAG21, 解説書-v4-202210

#1754 WCAG 2.1解説書（2022年9月版更新）：3.1.5: 読解レベル
  understanding/reading-level.html
Labels: 解説書-v4-202210

#1762 WCAG 2.1解説書（2022年9月版更新）：3.2.5: 要求による変化
  understanding/change-on-request.html
Labels: 解説書-v4-202210

#1716 用語集：特定の感覚的な体験の修正
  guidelines/index.html
  understanding/non-text-content.html
Labels: WCAG21, 解説書-v4-202210

#1717 用語集：利用者が制御可能の修正
  guidelines/index.html
  understanding/error-prevention-legal-financial-data.html
Labels: WCAG21, 解説書-v4-202210

#1741 用語集：ウェブページの修正
  guidelines/index.html
  understanding/bypass-blocks.html
  understanding/conformance.html
  understanding/consistent-navigation.html
  understanding/content-on-hover-or-focus.html
  understanding/error-prevention-all.html
  understanding/error-prevention-legal-financial-data.html
  understanding/focus-order.html
  understanding/headings-and-labels.html
  understanding/info-and-relationships.html
  understanding/label-in-name.html
  understanding/language-of-page.html
  understanding/link-purpose-in-context.html
  understanding/location.html
  understanding/multiple-ways.html
  understanding/non-text-content.html
  understanding/non-text-contrast.html
  understanding/page-titled.html
  understanding/three-flashes-or-below-threshold.html
  understanding/three-flashes.html
Labels: WCAG21, 解説書-v4-202210

#1742 用語集：アクセシビリティ サポーテッドの修正
  guidelines/index.html
  understanding/conformance.html
  understanding/link-purpose-in-context.html
  understanding/motion-actuation.html
Labels: WCAG21, 解説書-v4-202210

#1774 WCAG 2.1解説書（2022年9月版更新）：3.3: 入力支援
  understanding/input-assistance.html
Labels: 解説書-v4-202210

#1775 WCAG 2.1解説書（2022年9月版更新）：3.3.1: エラーの特定
  understanding/error-identification.html
Labels: 解説書-v4-202210

#1777 WCAG 2.1解説書（2022年9月版更新）：3.3.3: エラー修正の提案
  understanding/error-suggestion.html
Labels: 解説書-v4-202210

#1771 用語集：適合の修正
  guidelines/index.html
  understanding/abbreviations.html
  understanding/audio-control.html
  understanding/bypass-blocks.html
  understanding/change-on-request.html
  understanding/character-key-shortcuts.html
  understanding/conformance.html
  understanding/content-on-hover-or-focus.html
  understanding/link-purpose-in-context.html
  understanding/link-purpose-link-only.html
  understanding/motion-actuation.html
  understanding/pointer-cancellation.html
  understanding/pronunciation.html
  understanding/unusual-words.html
  understanding/visual-presentation.html
Labels: WCAG21, 解説書-v4-202210

#1772 解説書1.3.1「下記」に修正
  understanding/sensory-characteristics.html
Labels: 解説書-v4-202210

#1773 解説書3.2.2remainの修正
  understanding/on-input.html
Labels: 解説書-v4-202210
